net-snmp/net-snmp

- perl/SNMP/SNMP.pm
Just a little thing. But it took me friggin' _hours_ of trial and error to figure out...
> perl: Document format of SecEngineId

- snmplib/transports/snmpTLSBaseDomain.c
Both the subject and the issuer of a failed certificate is added
to the logged error message, so that troubleshooters have
details of which certificate is being rejected.
Fixes https://github.com/net-snmp/net-snmp/issues/248.
> Add certificate subject/issuer to verification error message.

- apps/snmptrapd.c
The snmptrapd expects gid directly. This behavior is different than the
snmpd, which instead expects the group name. The patch will make
snmptrapd behave in the same way as snmpd.
> Make snmptrapd expect group name instead of gid

- fuzzing/README.md
Add README for the fuzzers following the suggestion of @bvanassche here: https://github.com/net-snmp/net-snmp/pull/321#issuecomment-889286308
> Add README to fuzzing set up

- fuzzing/snmp_config_fuzzer.c
> Add config parser fuzzer

- testing/fuzzing/snmp_config_mem_fuzzer.c
Add fuzzer that target read_config_read_memory
> Fuzzing: Add config memory read fuzzer

- testing/fuzzing/snmp_parse_fuzzer.c
This will allow the fuzzer to explore further in the code as it is currently stock since no secmod modules are registered.
> fuzzing: extend parse fuzzer

- testing/fuzzing/snmp_e2e_fuzzer.c
Add end-to-end fuzzer inspired by snmppcap
> testing/fuzzing: Add end-to-end fuzzer

- snmplib/transports/snmpTLSBaseDomain.c
Currently SAN with IP is supported only in client certificates. (Verified by the agent)
Now server side certificates can also be verified with IP using Subject Alternative Names. 
According to rfc6353, Common Name verification is deprecated. 
So I am not sure if we should also set the X509_CHECK_FLAG_NEVER_CHECK_SUBJECT flag?
... but it would change the current behavior
For more details about used flags:
https://www.openssl.org/docs/man1.1.0/man3/X509_check_host.html
> TSM with TLS: Support Subject Alternative with IP 

- testing/fuzzing/snmp_print_var_fuzzer.c
Add fuzzer which targets print_variable and snprintf functions
> testing/fuzzing: Add fuzzer for print functions

- apps/snmpnetstat/inet.c
I think it's better to remove the extra branching in the condition and merge them
> apps: combining conditions

- mibs/IANA-ADDRESS-FAMILY-NUMBERS-MIB.txt
- mibs/IANAifType-MIB.txt
- mibs/UCD-SNMP-MIB.txt
Hi,
this has updates for the IANA mibs, and a missing REVISION entry tha was missed when UCD-SNMP-MIB was updated a couple of years ago.
/Niels
> V5 9 patches

- agent/mibgroup/hardware/fsys/fsys_mntent.c
> HOST-RESOURCES-MIB: Add overlay support

- agent/mibgroup/mibII/interfaces.c
- agent/mibgroup/mibII/ip.c
- agent/mibgroup/mibII/ipv6.c
- agent/mibgroup/mibII/tcp.c
- agent/mibgroup/mibII/tcpTable.c
- agent/mibgroup/mibII/udp.c
- agent/mibgroup/mibII/udpTable.c
- agent/mibgroup/ucd-snmp/memory_netbsd1.c
- include/net-snmp/system/netbsd.h
Some of these inspired by (taken from) the NetBSD pkgsrc patches.
> Updates for NetBSD 10 (now in Beta)

- snmplib/transports/snmpTLSBaseDomain.c
The function SSL_CTX_add_extra_chain_cert frees the used X509 pointer after destroying the associated SSL_CTX according to https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_add_extra_chain_cert.html. This leads to the X509 pointer from the cert-map being freed, while still being potentially used in further sessions. This problem regularly occurs, when repeatedly opening and closing netsnmp-sessions in a TSM/TLS-configuration.
I added a fix, where I create a copy of the original X509 pointer using X509_dup, which is used in SSL_CTX_add_extra_chain_cert instead of the cached X509 pointer and autonomously cleaned up by openssl after destroying the SSL_CTX.
Had some issues with my original PR #515. Reopened with source-branch being the forked master branch.
> Added fix for TSM segfault.

- testing/fulltests/default/T032snmpv3engineidchange_simple
This test validates commit 45a6422
> Added tests to validate SIGHUP for exactEngineID change

- agent/mibgroup/agentx/master_admin.c
master_admin.c: Validate that init_agent_snmp_session() was successful
> master_admin.c: Validate that init_agent_snmp_session() was successful

- man/netsnmp_config_api.3.def
netsnmp_config_api.3.def: Spelling and grammar
> netsnmp_config_api.3.def: Spelling and grammar

- agent/mibgroup/disman/nslookup/lookupCtlTable.c
Check a few more memory allocations
> lookupCtlTable.c: Check mallocs

- snmplib/snmpusm.c
Adds additional validation to snmpusm.c.
Fixes #734.
> snmpusm.c: Improve usm_read_user()'s error handling

- perl/SNMP/SNMP.xs
> Perl: added deallocation of session in error handling path

- agent/mibgroup/hardware/memory/memory_netbsd.c
- agent/snmpd.c
- apps/encode_keychange.c
- apps/snmpdelta.c
- apps/snmpnetstat/if.c
- apps/snmpnetstat/inetx.c
- apps/snmpnetstat/route.c
- apps/snmpnetstat/routex.c
- apps/snmptable.c
- apps/snmptrap.c
- apps/snmptrapd.c
- configure
- configure.d/config_os_headers
- include/net-snmp/net-snmp-config.h.in
- snmplib/transports/snmpUDPDomain.c
- snmplib/transports/snmpUDPIPv6Domain.c
Fixing warnings, mostly OpenBSD, NetBSD.
> V5-9-patches

- agent/helpers/scalar.c
Fixes: e2ea345fa783(Agent helper module for support of scalar objects.)
Found by RASU JSC with ISPRAS Svace
> agent: helpers: added allocation fail check

- apps/sshtosnmp.c
Completes 3346619 (libsnmp: Port the SSH domain transport to FreeBSD)
Second iteration
> Port sshtosnmp to FreeBSD.

- agent/mibgroup/ucd-snmp/lmsensorsMib.c
- agent/mibgroup/ucd-snmp/lmsensorsMib.h
- mibs/LM-SENSORS-MIB.txt
> Update LM-SENSORS-MIB to support negative temperatures

- include/net-snmp/types.h
- snmplib/snmp_api.c
- snmplib/snmp_debug.c
Added checks to allow for building to qnx
> Added qnx support

- agent/mibgroup/mibII/tcp.c
Patch taken from FreeBSD ports collection.
> Fix build for FreeBSD 15.
