net-snmp/net-snmp

- agent/mibgroup/host/data_access/swinst_rpm.c
- agent/mibgroup/host/hr_swinst.c
Based on the RHEL Bugzilla, Adding the rpmFreeRpmrc() before the exit function solves the memory leak if the function calls the rpmReadConfigFiles(). The sniff test at my side works fine.
> Solve the memory leak in RHEL8

- include/net-snmp/library/mib.h
This will allow compilation using C++17 where the register keyword is obsoleted.
Also, the register keyword is in general never necessary.
> Remove obsolete keyword.

- agent/mibgroup/disman/ping/pingCtlTable.c
- agent/mibgroup/disman/ping/pingCtlTable.h
> pingCtlTable: Move two more global variable definitions from .h to .c

- agent/mibgroup/ucd-snmp/proxy.c
This PR resolves the issue #147.
The test scenario presented in the issue no longer fails with this fix in place.
Without a complete understanding of the actual expected flow, I can not tell if there are any side effects such as leaks or locks in other scenarios.
A short explanation of the fix intent is provided in the code.
> Issue#147: Net-SNMP not responding when proxy requests times out

- agent/mibgroup/hardware/sensors/lmsensors_v3.c
LM-SENSORS-MIB supports only 4 standard sensors but provides MISC table
for other sensors, we can use that table to log the humidity sensor
reading.
Tested using my local unit and works fine.
> sensors: Add support for humidity sensor

- perl/agent/agent.xs
The code is currently very strict, and does not accept several internal perl representations for integer scalars. This is a problem when writing SNMP agents in perl as the values might come from external sources and might be represented internally in multiple ways, which might change over the course of the execution.
In addition improve the logging output to make it easier to diagnose why a scalar variable could not be set.
This was  initially posted at https://sourceforge.net/p/net-snmp/code/merge-requests/7/ some time ago, but I guess it fell through the cracks. :)
> Make the perl agent code more tolerant of perl types

- perl/SNMP/SNMP.xs
```c
void
snmp_session_DESTROY(sess_ptr)
void *sess_ptr
```
in this block sess_ptr MUST be defined as SnmpSession *
```c
void
snmp_session_DESTROY(sess_ptr)
SnmpSession *sess_ptr
```
here is a results of conversion .xs to .c for this code
for void *
```c
void *  sess_ptr = INT2PTR(void *,SvIV(ST(0)))
```
for SnmpSession *
```c
SnmpSession *   sess_ptr;
if (SvROK(ST(0))) {
IV tmp = SvIV((SV*)SvRV(ST(0)));
sess_ptr = INT2PTR(SnmpSession *,tmp);
}
else
Perl_croak_nocontext("%s: %s is not a reference",
"SnmpSessionPtr::DESTROY",
"sess_ptr")
```
destructor calls snmp_close or snmp_sess_close with absolutely wrong parameter and we have a huge resource leak
code creates new SV and RV but uses it only inside the comparison branch
this problem can be reproduced using script and command line from …
> fix resource leaks in the SNMP::Session destructor and SNMP::NODE::FETCH

- agent/mibgroup/host/hr_filesys.c
On non-AIX systems without getfsstat, a variable is being declared right
after a label. This is a violation of the C language standard, and
causes the following compile error:
host/hr_filesys.c: In function 'Get_Next_HR_FileSys':
host/hr_filesys.c:752:5: error: a label can only be part of a statement and a declaration is not a statement
const char    **cpp;
^~~~~
Fix the problem by adding an empty statement after the label.
Fixes: 22e1371bb1fd ("HOST-MIB, hr_filesys: Convert recursion into iteration")
Signed-off-by: Stijn Tintel <stijn@linux-ipv6.be>
> HOST-MIB, hr_filesys: fix compile error

- agent/mibgroup/hardware/memory/memory_freebsd.c
This fixes a memory reporting problem under FreeBSD, which the FreeBSD port has relied on as a patch for many years.
> Include inactive memory with cache under FreeBSD; Fixes #205

- include/net-snmp/library/snmp_logging.h
- snmplib/snmp_logging.c
Fix compilation when feature NETSNMP_FEATURE_REMOVE_LOGGING_STDIO is used. Currently when this feature is set in include/net-snmp/net-snmp-config.h, according to INSTALL instructions, the program won't build. This fixes this problem.
> Fix compilation with feature NETSNMP_FEATURE_REMOVE_LOGGING_STDIO

- include/net-snmp/library/cert_util.h
- snmplib/cert_util.c
- snmplib/transports/snmpTLSBaseDomain.c
In a typical PEM encoded trust store, certificates are listed one
after the other in the same file. Lift the restriction that only
the first matching trusted certificate is trusted, and instead
trust all certificates that match a given PEM file.
This allows net-snmp to be used with standard PKI, such as Let's
Encrypt.
Fixes https://github.com/net-snmp/net-snmp/issues/245
> Allow trusting of more than one certificate per file

- snmplib/cert_util.c
The allowed_uses field for each certificate sets whether the certificate
is a CA certificate, could be used as an identity, or as a peer
certificate.
This field is only set correctly on the first pass when indexing
certificates, or when debug mode is on. The effect is that certificates
are not found when they should be, but only sometimes.
This patch adds the allowed_uses field to the index, so the value is
available consistently throughout.
Fixes https://github.com/net-snmp/net-snmp/issues/255
> Index the allowed_uses field for each certificate

- snmplib/transports/snmpUDPDomain.c
- snmplib/transports/snmpUDPIPv6Domain.c
This fixes issue, that is caused by parsing IP address twice. First as IPv4 and as IPv6 at second, even though the address was
properly parsed as a valid IPv4 address. See issue #199 for more details
> Prevent parsing IP address twice (#199)

- local/net-snmp-cert
> Use sha512 as default option for generating certificates.

- agent/agent_trap.c
- agent/mibgroup/notification/snmpNotifyTable_data.c
- agent/mibgroup/target/snmpTargetAddrEntry_data.c
- agent/mibgroup/target/snmpTargetAddrEntry_data.h
- include/net-snmp/agent/agent_trap.h
See also: https://github.com/net-snmp/net-snmp/issues/187
Re-opening of TCP connection with snmptrapd is still not supported.
> Fix the crash of snmpd when snmptrapd terminates the TCP connection.

- include/net-snmp/library/snmp_transport.h
- snmplib/transports/snmpUDPIPv4BaseDomain.c
- snmplib/transports/snmpUDPIPv6Domain.c
For example if snmptrapd is UDP socket-activated, it still tries to bind the
socket passed in by systemd.  This is not permitted (the default port is "low",
thus privileged) and also invalid, because the port is already taken by systemd.
Since the code handling UDP is structured differently than TCP, that
method isn't directly applicable, but I tried to copy the idea as far as
possible. Other solutions are certainly possible if preferred.
> Enable systemd socket activation for UDP sockets

- python/setup.py
This prevents setup.py from discovering wrong library link options (`-l`, `-L`) in the middle of a word, like `"inux-gnu"` from `"-L/usr/lib/x86_64-linux-gnu"`.
For `net-snmp-config` output as follows (real world example from Ubuntu 18.04):
```
-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -L/usr/lib/x86_64-linux-gnu -lnetsnmp -lcrypto -lm
```
the former regex `-l(\S+)` would match to
```python
['inux-gnu', 'netsnmp', 'crypto', 'm']
```
which obviously results in a ld error `cannot find -linux-gnu`.
Now we capture a string only, if `-l` is at the beginning of a string, or if `-l` is preceded by any number of whitespace characters.
> Fix regex for "-l" discovery in setup.py

- agent/mibgroup/host/data_access/swrun.c
- agent/mibgroup/if-mib/data_access/interface.c
- agent/mibgroup/struct.h
- agent/mibgroup/ucd-snmp/proc.c
- include/net-snmp/data_access/interface.h
HAVE_PCRE_H is undefined if <pcre.h> could or should not be used.
Fix compiler warnings / errors if compiled with the compiler flags
-Wundef or -Werror=undef.
> Fix inconsistent use of #if vs. #ifdef HAVE_PCRE_H

- perl/agent/agent.xs
This PR includes few fixes and improvements to the setValue() value conversion by using a scaled epsilon to check for rounding relative errors, and logging more useful double values, and adding missing newlines.
> Perl agent: setValue() value conversion and logging improvements

- configure
- configure.d/config_project_perl_python
Fixes: https://sourceforge.net/p/net-snmp/patches/1375/
The net-snmp configure script imposes restrictions on the name of the compiler that was used to compile perl. Particularly, it does not allow the name to contain a period. If it does, the perl module is not built. This is what happens on Mac OS X 10.6 when perl was built with `/usr/bin/gcc-4.2`:
```
checking if we are in the source tree so we can install Perl modules... Yes
checking for Perl cc... checking for potential embedded Perl support... disabled
checking if we can install the Perl modules... no
```
This PR fixes the configure script to allow periods in the compiler name, and now the output is:
```
checking if we are in the source tree so we can install Perl modules... Yes
checking for Perl cc... /usr/bin/gcc-4.2
checking …
```
> Allow perl compiler name to contain periods

- local/mib2c-update
When the path name includes space, the script will create the wrong directories.
```bash
$ cd "/path/to/foo bar"
$ mib2c-update
```
```
/usr/bin/mib2c-update: line 311: [: /path/to/foo: binary operator expected
creating example .mib2c-udpaterc. edit as needed and re-run
mib2c-update.
Creating missing directory /path/to/foo
Creating missing directory bar
Creating missing directory bar/.orig
Creating missing directory bar/.new
Creating missing directory bar/.merged
Creating missing directory bar/.patch
Creating missing directory bar/.backup
Creating missing directory bar/.backup/curr
Creating missing directory bar/.backup/orig
ERROR: Environment variable missing! Set UPDATE_OID in .mib2c-updaterc
ERROR: Environment variable missing! Set UPDATE_CONF in .mib2c-updaterc
ERROR: WARNING: mib2c …
```
> mib2c-update: Fix misbehavior when the path includes space

- fuzzing/agentx_parse_fuzzer.c
- fuzzing/parse_octet_hint_fuzzer.c
- fuzzing/read_objid_fuzzer.c
- fuzzing/snmp_mib_fuzzer.c
- fuzzing/snmp_parse_fuzzer.c
- fuzzing/snmp_parse_oid_fuzzer.c
- fuzzing/snmp_pdu_parse_fuzzer.c
- fuzzing/snmp_scoped_pdu_parse_fuzzer.c
Migrate fuzzers from the oss-fuzz repository to the net-snmp repository. We discussed this briefly over the mailing list and this PR in combination with the one in the oss-fuzz repo https://github.com/google/oss-fuzz/pull/6113 achieves it
I also made the build script in oss-fuzz more general such that we can simply add new fuzzers in the `fuzzing` directory in the net-snmp repository by having a `_fuzzer.c` suffix. 
@fenner @bvanassche
> migrate fuzzers from oss-fuzz repo.

- agent/mibgroup/ucd-snmp/pass_common.c
According to the MAN page of [snmpd.conf](http://www.net-snmp.org/docs/man/snmpd.conf.html) pass_persist protocol of a set-request consists of exactly three lines:
> For SET requests, PROG will be passed three lines on stdin, the command (set) and the requested OID, followed by the type and value (both on the same line).
In contrast to this specification recent versions of snmpd behave differently:
A set-request to a pass_persist script contains an additional _Newline_ character ("\n"), which leads to a wrong answer (no such name) to the following get-request.
Below is a communication trace between the SNMP agent (snmpd) and an example pass_persist scripts:
read(0, "PING\n", 8192) = 5
write(1, "PONG\n", 5) = 5
read(0, "set\n.1.3.6.1.4.1.xxxx.1.2.3.0\nstring \"Demo Text\"\n\n", 8192) = 76 …
> remove additional new line character in set-requests to pass_persist scripts

- include/net-snmp/ada_fuzz_header.h
- testing/fuzzing/snmp_api_fuzzer.c
@bvanassche this PR adds a new API fuzzer. The fuzzer relies on a small library that makes fuzzer-writing easier by taking care of extracting various data types, e.g. null-terminated strings, seeded with fuzzer input. The library is available here: https://github.com/AdaLogics/fuzz-headers and I use it to fuzz other important OSS projects, e.g. Apache-httpd, and soon also OpenVPN and more. I would be very happy to continue using that library for writing net-snmp fuzzers. However, I see that you are refining the infrastructure around building fuzzers so am not entirely sure where I should include downloading the small library (it's just a header file for now). Could you perhaps elaborate a bit on how you prefer to have the build scripts? I could also help with migrating the build scripts …
> fuzzing: add new api fuzzer

- snmplib/snmp_api.c
Ensure 'ix' is in range of 'buf' so the code 'buf[ix] |= bit;' is valid.
This fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37564
> libsnmp: Fix spurious buffer read

- snmplib/mib.c
Prevent that cp2 reads past end of the cp buffer. This patch fixes
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=36874
> libsnmp: Fix a read-past-end-of-buffer

- snmplib/parse.c
Ensure the code `get_token(fp, nexttoken, nexttype);` does not have
nexttype larger than MAXTOKEN as otherwise nexttoken can overflow.
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37187
> libsnmp: Fix stack-based buffer overflow

- testing/fuzzing/ada_fuzz_header.h
Declare functions in fuzz helper to remove warnings during build.
> testing/fuzzing: Declare functions in fuzz helper

- testing/fuzzing/build.sh
- testing/fuzzing/snmp_transport_fuzzer.c
Add transport fuzzer which was previously removed because it used
undeclared functions (https://github.com/net-snmp/net-snmp/pull/366).
> testing/fuzzing: Add transport fuzzer

- agent/mibgroup/agentx/protocol.c
Ensure strlen is equal to community_len before the code
```
pdu->contextName    = strdup((char *) pdu->community);
pdu->contextNameLen = pdu->community_len;
```
This ensures `contextNameLen` is not above the size of the buffer returned by `strdup`.
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=40431
> snmpd: Ensure contextNameLen follows buffer size

- snmplib/parse.c
Ensure `strlen(defbuf)` is above zero before the code
`defbuf[strlen(defbuf) - 1] = 0;`
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=40699
> libsnmp: Fix stack-based buffer underflow

- testing/fuzzing/agentx_parse_fuzzer.c
> testing/fuzzing: Fix cast to avoid compiler warning

- testing/fuzzing/snmp_transport_fuzzer.c
This patch ensures the fuzzer calls cleanup code before returning.
> testing/fuzzing: Free allocated objects in fuzz code

- include/net-snmp/library/default_store.h
- man/snmpd.conf.5.def
- snmplib/transports/snmpTLSBaseDomain.c
- snmplib/transports/snmpTLSTCPDomain.c
Until now, it has been limited to TLS1.0, which is no longer considered secure. I have also increased default minimum configuration to TLS1_2
Format for configuration options (tls1 | tls1_1| tls1_2 | tls1_3) similar to openssl s_client command
> [TSM] TLS TCP Support the configuration of min/max tls version

- agent/mibgroup/hardware/fsys/fsys_mntent.c
virtiofs is a relatively new virtual filesystem. At present, it is misdetected by net-snmp and needs to be added to the other_fs array.
> Add virtiofs to other_fs

- snmplib/transports/snmpTCPDomain.c
- snmplib/transports/snmpTCPIPv6Domain.c
It's based on the 02de400544dea6804c348c457a5ea5ea5531b12d for fixes an issue #12 with TCP transport
(fix #389)
Signed-off-by: Dmitrii Turlupov <dturlupov@factor-ts.ru>
> libsnmp: Set Linux VRF iface on Trap sink IP addresses for TCP transport

- testing/fuzzing/snmp_transport_fuzzer.c
This patch fixes an unexpected-exit issue
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=40640 which
is likely the cause of a coverage failure issue
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46588
The problem is netsnmp_tdomain_transport_full eventually forks the
process and also calls exit, which is not compatible with fuzzing. As
such, the function should not be called by the fuzzer.
> testing/fuzzing: fix transport fuzzer coverage

- testing/fulltests/support/simple_eval_tools.sh
Not all implementations of getopt() handle options appearing after
operands. POSIX doesn't require that, it's a GNU extension.
Running the testsuite from version 5.9.2+ on such a system results in
even simple tests failing as the agent attempts to find to port "-f"
```
trace: netsnmp_agent_listen_on(): /data/omnios-build/omniosorg/bloody/_build/net-snmp-5.9.3/net-snmp-5.9.3/./agent/snmp_agent.c, 1418:
snmp_agent: init_master_agent; "udp:127.0.0.1:8799" registered as an agent NSAP
trace: init_master_agent(): /data/omnios-build/omniosorg/bloody/_build/net-snmp-5.9.3/net-snmp-5.9.3/./agent/snmp_agent.c, 1510:
snmp_agent: installing master agent on port -f
```
> testing/fulltests/support/simple_eval_tools.sh: support non-GNU getopt

- snmplib/parse.c
tclist is always allocated in netsnmp_init_mib_internals, when doing multiple init_snmp("")/snmp_shutdown("") this memory is never free'd.
> unload_all_mibs: fix memory leak by freeing tclist

- agent/mibgroup/ip-mib/data_access/scalars_linux.c
An incorrect error check was causing failures to modify ipDefaultTTL when an integer with more than one digit is passed:
`
$ snmpget -v 2c -c private localhost .1.3.6.1.2.1.4.2.0
IP-MIB::ipDefaultTTL.0 = INTEGER: 64
$ snmpset -v 2c -c private localhost .1.3.6.1.2.1.4.2.0 i 128
Error in packet.
Reason: undoFailed
Failed object: IP-MIB::ipDefaultTTL.0
$ snmpset -v 2c -c private localhost .1.3.6.1.2.1.4.2.0 i 8
IP-MIB::ipDefaultTTL.0 = INTEGER: 8
$ snmpget -v 2c -c private localhost .1.3.6.1.2.1.4.2.0
IP-MIB::ipDefaultTTL.0 = INTEGER: 8
$ snmpset -v 2c -c private localhost .1.3.6.1.2.1.4.2.0 i 64
Error in packet.
Reason: (genError) A general failure occured
Failed object: IP-MIB::ipDefaultTTL.0
$ snmpget -v 2c -c private localhost .1.3.6.1.2.1.4.2.0
IP-MIB::ipDefaultTTL.0 = INTEGER: 8
`
> ip-mib: Fix incorrect error handling for ipDefaultTTL sets

- apps/snmpping.c
In default case dest wasn't freed, although in the current code this is hardly possible, here is potential problem
> apps: fix handle leak

- apps/snmptrapd_sql.c
**[Environment]**
MySQL server v8.0.31
Snmptrapd v5.10
**[Issue]**
wait_timeout is the number of seconds the MySQL server waits for activity before closing the connection.
Snmptrapd cannot reconnect to the MySQL server once the connection is closed.
**[Root Cause]**
Snmptrapd can reconnect to the MySQL server by using MySQL v5.7.40.
The new version of MySQL writes the reason for the connection before closing it, and the client receives a more informative error message (ER_CLIENT_INTERACTION_TIMEOUT).
Snmptrapd does not handle this error code, so the connection will not reconnect to the MySQL server.
**[Solution]**
The implementation of mysql_real_connect may be changed, so only handling the error code can not solve the problem.
We should close the existing connection and reinitialize it …
> Snmptrapd cannot reconnect to MySQL server after hitting MySQL wait_timeout

- agent/snmp_agent.c
- apps/snmpset.c
- testing/fulltests/default/T0142snmpv2csetnull_simple
I'm creating a pull request here just to solicit reviews - I can obviously commit myself if we decide this is right.
This is my reaction to #474 and #475 - both of these are because the SET code doesn't check the incoming type at all, and assume that the integer member of the union is set.  But for a NULL type, the pointer is NULL.
There are still problems with MIB module implementations that do not check the varbind type - what does it mean to set the ipDefaultTTL to an OBJECT-IDENTIFIER?  So there are still opportunities for cleanup; every SET_RESERVE1 should call `netsnmp_check_vb_type()` - but NULL is the only case where the pointer will be invalid, so this patch eliminates the possibility that a module implementation will naively dereference a NULL pointer.
> Disallow SET requests with NULL varbind

- snmplib/snmp_openssl.c
This avoids the need for all the clumsy (and unchecked) pointer casts. OpenSSL also since deprecated the old names for the symbols (the underlying sk_num is now OPENSSL_sk_num), so this removes references to some deprecated names.
> Use the typed wrappers for STACK_OF(X509)

- snmplib/snmpv3.c
As per order of [function evaluation](https://en.cppreference.com/w/c/language/eval_order) it is up to the compiler to decide which function is executed first. As  `snmpv3_local_snmpEngineTime()` can increase engineBoot which is later taken from `snmpv3_local_snmpEngineBoots` there can be some issues during restart.
Please note that `set_enginetime()` function saves engineBoot taken as an argument and saves it in Enginetime list which is later used to generate response message and fill fields like engineBoots and engineTime. As per below code we can have two possibilites after restart.
1. `snmpv3_local_snmpEngineTime()` is executed first. EngineBoot is increased to 2 and then `snmpv3_local_snmpEngineBoots` returns 2 and everything works correctly.
2. `snmpv3_local_snmpEngineBoots` is …
> Fix order of evaluation during init

- configure
- configure.d/config_os_progs
Commit cb9b87d9b6e2 ("Always use -Wl,-no-undefined when linking a shared library") swaps the libtool flag -no-undefined for the linker flag -Wl,-no-undefined on Cygwin.
These two aren't the same: ld's -no-undefined flag [1] makes unresolved references an error [1], whereas libtool's -no-undefined flag [2] assures it that there are no undefined references and therefore it may try to build a shared library on platforms where that is required to build a shared library.
[1] https://sourceware.org/binutils/docs-2.40/ld/Options.html
[2] https://www.gnu.org/software/libtool/manual/html_node/Link-mode.html#Link-mode
This flag possibly should also be used for MinGW builds, if shared libraries are wanted there.
> Restore using libtool's -no-undefined flag on Cygwin

- configure.d/config_net_snmp_config_h
See https://gcc.gnu.org/onlinedocs/cpp/_005f_005fhas_005fattribute.html
This fixes the build for RHEL7
> configure: fix test for __has_attribute

- include/net-snmp/library/mib.h
netsnmp_get_mib_directory was already exported, but netsnmp_set_mib_directory was not.
Now any external application can set its MIB dirs without reimplementing the netsnmp_set_mib_directory function.
closes #530
> libsnmp: Export netsnmp_set_mib_directory so it can be used inside a custom application.

- configure.d/config_os_functions
- man/snmpd.conf.5.def
- snmplib/transports/snmpUDPDomain.c
The openSUSE/SUSE net-snmp v5.7 package had a feature to use netgroups defined in `/etc/netgroup` or NIS/LDAP to gain access to a SNMP host. This feature was ported to our v5.9 and I would like to get it into the master branch.
How this feature works:
```
/etc/netgroup
nodes (node1,,) (node2,,) (node3,,)
/etc/snmp/snmpd.conf
rocommunity public @nodes
```
This makes it easier to define host groups that should have access to the SNMP host.
> Add '@' netgroup functionality

- configure.ac
- perl/MakefileSubs.pm.in
Setting the flags at configure time instead of runtime allows use of the perl module without pulling in net-snmp-config (which in the Fedora/RHEL RPM setup also pulls in gcc and *-devel packages, not otherwise needed when just using the perl SNMP module).  The in-tree module is updated with the rest of the net-snmp code anyway, so setting this at configure time should stay consistent.
> Set flags in MakefileSubs.pm at configure time

- agent/mibgroup/host/data_access/swrun.c
- agent/mibgroup/if-mib/data_access/interface.c
- agent/mibgroup/struct.h
- agent/mibgroup/ucd-snmp/proc.c
- agent/mibgroup/ucd-snmp/proc.h
- configure.d/config_os_libs1
- configure.d/config_project_with_enable
- include/net-snmp/data_access/interface.h
- include/net-snmp/data_access/swrun.h
- include/net-snmp/types.h
the dutchman was insistent i create a "pull request", which wasn't so bad once i read closer, but i wish my patch was embraced unconditionally. 
BUT, i digress. original message is here below:
hi,
my boy a*s**ck (@brainslayer) has decided to update snmp, and i noticed there is a small chunk of code using pcre for interface searching (or something like that).
as such, i've attached a patch that should provide proper pcre2_support.
an aside: i noticed i had to remove the "#ifdef" macros for PCRE in interface.h, as i'd get some configuration error that would prevent the interface.c/interface.h (and associated files) from being built. i found it very unusual. it could be the fact i'm on a mac and cross-compiling. not sure. i hope someone else can figure out any problems with my modifications …
> add pcre2 support

- agent/snmpd.c
SNMP operations continue to work with old engine-id with SIGHUP.
> Handle SIGHUP for engine-id change

- agent/mibgroup/host/data_access/swinst_rpm.c
- agent/mibgroup/host/hr_swinst.c
From RPM 4.16 the SQLite support is available for RPM DB. After https://fedoraproject.org/wiki/Changes/Sqlite_Rpmdb, rpm changed it's background DB from Berkeley to SQLite in Fedora. Net-SNMP is using hard coded paths to determine where RPM DB files are.
This update is adding check for rpmdb.sqlite file in order to be able invalidate internal cache after system package change.
Closes #596
> Add support for RPM SQLite DB background.

- agent/mibgroup/disman/ping/pingResultsTable.c
pingResultsTable.c: Fix memory leaks (Coverity 85662)
Free memory allocation referenced in StorageTmp that is not free()'d in the event of a failure
> pingResultsTable.c: Fix memory leaks (Coverity 85662)

- agent/mibgroup/disman/ping/pingCtlTable.c
pingCtlTable.c: Fix memory leaks (Coverity 85603)
Free allocated memory if an error occurs.
> pingCtlTable.c: Fix memory leaks (Coverity 85603)

- agent/mibgroup/disman/nslookup/lookupResultsTable.c
lookupResultsTable.c: Fix memory leaks (coverity 85588)
Free memory allocation referenced in StorageTmp that is not free()'d in the event of a failure
> lookupResultsTable.c: Fix memory leaks (coverity 85588)

- agent/mibgroup/mibII/icmp.c
icmp.c: Fix memory leaks (Coverity 85667)
Free memory allocation referenced in msg_stats_table_info that is not free()'d in the event of a failure
> icmp.c: Fix memory leaks (Coverity 85667)

- agent/mibgroup/notification/snmpNotifyFilterProfileTable_data.c
snmpNotifyFilterProfileTable_data.c: Fix memory leaks (Coverity 85636)
Free memory allocation referenced in StorageTmp that is not free()'d in the event of a failure
> snmpNotifyFilterProfileTable_data.c: Fix memory leaks (Coverity 85636)

- agent/mibgroup/disman/nslookup/lookupCtlTable.c
Avoid leaking memory referenced in address if an invalid argument is passed in.
> lookupCtlTable.c: Fix memory leak (Coverity 85698-4)

- agent/helpers/table_dataset.c
Free memory allocation referenced in table_info that is not free()'d in the event of a failure
> table_dataset.c: Fix memory leak (Coverity 144371)

- agent/mibgroup/deliver/deliverByNotify.c
Avoid leaking memory referenced in vars if it fails to issue the query.
> deliverByNotify.c: Fix memory leak (Coverity 144379)

- agent/mibgroup/ip-forward-mib/data_access/route_linux.c
route_linux.c: Fix memory leak (Coverity 344582)
Avoid leaking memory referenced in entry if the IPv6 data is formatted incorrectly.
> route_linux.c: Fix memory leak (Coverity 344582)

- agent/mibgroup/examples/netSnmpHostsTable.c
netSnmpHostsTable.c: Fix memory leak (Coverity 344583)
Free memory allocation referenced in my_handler that is not free()'d in the event of a failure.
> netSnmpHostsTable.c: Fix memory leak (Coverity 344583)

- agent/mibgroup/mibII/icmp.c
Set the variable msg_stats_table_info to a default value of NULL, to avoid potentially accessing the pointer when it's uninitialized
> icmp.c: Avoid uninitialized variable error

- snmplib/transports/snmpUnixDomain.c
Free memory if recvfrom() fails.
Found with clang scan-build
> snmpUnixDomain.c: Free memory if recvfrom fails

- snmplib/snmpv3.c
Confirm snmpv3_generate_engineID() was successful before using data from it
If snmpv3_generate_engineID() fails, it returns NULL, possibly without modifying the passed-in engineIDLen parameter. This change examines the return value from snmpv3_generate_engineID() before examining the possibly-uninitialized engineIDLen.
Found with clang scan-build
> snmpv3.c: Confirm snmpv3_generate_engineID() was successful

- agent/mibgroup/agent/nsDebug.c
nsDebug.c: Fix memory leak (Coverity 85684)
Free memory allocation referenced in table_info that is not free()'d in the event of a failure
> nsDebug.c: Fix memory leak (Coverity 85684)

- agent/mibgroup/disman/expr/expValue.c
expValue.c: Fix memory leak (Coverity 85691)
Avoid leaking memory referenced in var if invalid parameters are passed in by only allocating memory if parameters are valid.
> expValue.c: Fix memory leak (Coverity 85691)

- agent/mibgroup/disman/event/mteTrigger.c
mteTrigger.c: Fix copy-paste bug (Coverity 85536)
Examine the proper variable when determining whether or not fire a fall event.
> mteTrigger.c: Fix copy-paste bug (Coverity 85536)

- agent/mibgroup/disman/event/mteTrigger.c
mteTrigger.c: Fix copy-paste bug (Coverity 85524)
Examine the proper variable when determining whether or not fire a fall event.
> mteTrigger.c: Fix copy-paste bug (Coverity 85524)

- agent/mibgroup/agentx/subagent.c
Avoid leaking memory referenced in smagic if snmp_clone_pdu fails.
> subagent.c: Fix memory leak (Coverity 357928)

- agent/mibgroup/disman/nslookup/lookupCtlTable.c
Avoid leaking memory referenced in StorageTmp if invalid data is passed in.
> lookupCtlTable.c: Fix memory leak (Coverity 85732)

- agent/mibgroup/disman/nslookup/lookupCtlTable.c
lookupCtlTable.c: Fix memory leak (Coverity 85698-3) Avoid leaking memory referenced in address if IPv6 DNS lookup fails.
> lookupCtlTable.c: Fix memory leak (Coverity 85698-3)

- agent/mibgroup/disman/nslookup/lookupCtlTable.c
lookupCtlTable.c: Fix memory leak (Coverity 85698-2) Avoid leaking memory referenced in address if IPv4 DNS lookup fails.
> lookupCtlTable.c: Fix memory leak (Coverity 85698-2)

- snmplib/read_config.c
Remove dead store detected by clang.
read_config.c:1454:26: warning: Value stored to 'ctmp' during its initialization is never read [deadcode.DeadStores]
struct config_files *ctmp = config_files;
> read_config.c: Remove dead store

- agent/mibgroup/tlstm-mib/snmpTlstmCertToTSNTable/snmpTlstmCertToTSNTable.c
snmpTlstmCertToTSNTable.c: Fix memory leak (Coverity 85750)
Avoid leaking memory referenced in watcher if netsnmp_create_handler_registration fails.
> snmpTlstmCertToTSNTable.c: Fix memory leak (Coverity 85750)

- snmplib/snmp_api.c
sourceFilterType and sourceFilterAddress options in snmpd.conf. However, once activated, internal requests are also blocked. The filtering is based on IP in the string returned by the function "fmtaddr". Internal requests do not have a source IP, instead of an IP address, the function returns a string that starts with "callback" following a file descriptor numero. These internal requests are generated by alarms to define event triggers. If they are blocked, no traps will be sent.
Therefore, do not filter internal requests by checking if the string returned by "fmtaddr" starts with "callback".
Fixes: 9d28612ac03b ("add packet filtering by source ip")
> snmplib: do not filter internal request

- agent/agent_registry.c
Avoid memory leak if strdup fails.
Also, return NULL to indicate that the object creation failed.
Kudos to [!404](https://github.com/net-snmp/net-snmp/pull/404)
> agent_registry.c: Avoid memory leak if strdup fails

- snmplib/snmp_transport.c
Ensure malloc() and strdup() were successful
> snmp_transport.c: Validate memory allocations

- agent/mibgroup/host/hr_swinst.c
This change is fixing memory leak when using RPMDB macros. The fix was introduced in PR #49 but was overwritten over time. Fix is needed in agent/mibgroup/host/hr_swinst.c only as the regression in the agent/mibgroup/host/data_access/swinst_rpm.c was fixed few weeks ago.
This is proposed solution for issue #652
> Fix regression of memory leak when using RPMDB macros.

- Makefile.top
Always use `--tag=CC` when invoking libtool with `--mode=compile` or `--mode=link` to avoid the error message "libtool: compile: unable to infer tagged configuration" when compiling with a different compiler than the one that was used to compile libtool.
Fixes #647
> Makefile.top: Use --tag=CC when invoking libtool

- agent/mibgroup/disman/ping/pingCtlTable.c
Ensure all memory allocations within create_pingCtlTable_data() were successful
> pingCtlTable.c: Validate create_pingCtlTable_data() allocations

- apps/snmpget.c
snmpget.c: Avoid leak if parsing OID fails. This leak would not normally cause any problems, but might make investigating other leaks more difficult
> snmpget.c: Avoid leak if parsing OID fails

- testing/fuzzing/parse_octet_hint_fuzzer.c
Fixes compiler warning:
Compiling testing/fuzzing/parse_octet_hint_fuzzer.c testing/fuzzing/parse_octet_hint_fuzzer.c:58:24: error: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Werror,-Wsign-compare]
assert(value_start <= size);
Everything else is a size_t, no reason to not have value_start as a size_t too
> parse_octet_hint_fuzzer.c: Use size_t for value_start

- testing/fuzzing/snmp_print_var_fuzzer.c
Fixes compiler warning:
Compiling testing/fuzzing/snmp_print_var_fuzzer.c
testing/fuzzing/snmp_print_var_fuzzer.c:260:23: error: comparison of integers of different signs: 'int' and 'unsigned long' [-Werror,-Wsign-compare]
for (int i = 0; i < strlen(snprint_hints); i++) {
> snmp_print_var_fuzzer.c: Use size_t for strlen index

- snmplib/snmpv3.c
snmpv3.c: Avoid leaking memory if command-line args are repeated
Specifically, -n, -u, -K, and -k
> snmpv3.c: Avoid leaking memory if command-line arg is repeated

- snmplib/snmpv3.c
snmpv3.c: Avoid leaking memory if -X or -A is repeated
> snmpv3.c: Avoid leaking memory if -X or -A is repeated

- snmplib/transports/snmpTLSBaseDomain.c
According to testssl tool (https://testssl.sh/), it is not ok when Server has not set a cipher order, see image below
> Adding server cipher order by default

- snmplib/snmpv3.c
snmpv3.c: Avoid leaking memory if -E or -e is repeated
Fixes #703
> snmpv3.c: Avoid leaking memory if -E or -e is repeated

- apps/snmpusm.c
> snmpusm.c: fix text phrasing

- configure
- configure.d/config_project_types
In Alpine Linux there is a compilation error due to an unknown type.
> Fix configuration of NETSNMP_FD_MASK_TYPE

- testing/fulltests/unit-tests/T102pdu_build_clib.c
T102pdu_build_clib.c: Fix memory leaks
> T102pdu_build_clib.c: Fix memory leaks

- testing/fulltests/unit-tests/T011snmp_old_api_registration_cagentlib.c
Avoid leaking session object, so another test passes with leak sanitizer enabled
> T011snmp_old_api_registration_cagentlib.c: Avoid leaking session object

- agent/mibgroup/examples/ucdDemoPublic.c
ucdDemoPublic.c: Fix memory leak (Coverity 85639)
Avoid leaking engineID
> ucdDemoPublic.c: Fix memory leak (Coverity 85639)

- snmplib/snmpusm.c
snmpusm.c: Fix segfault when parsing config file createUser line If no authentication profile is specified, use the default.
Fixes #416
> snmpusm.c: Fix segfault when parsing config file createUser line

- agent/agent_global_vars.h
> agent_global_vars.h: Remove redundant forward declaration

- snmplib/snmp_transport.c
> snmp_transport.c: Remove redundant if statement

- .github/workflows/coverity.yml
This prevents the Coverity scheduled job from automatically running in forked repos
`github.repository` is documented here: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
YAML entry is similar to here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-run-job-for-specific-repository
> coverity.yml: Only run in main repository

- testing/fulltests/unit-tests/T103pdu_parse_clib.c
Fixes issue #722 , by free()ing parsed PDU
> T103pdu_parse_clib.c: Fix memory leak in test

- snmplib/container.c
On low-end devices, there is no point to hold the memory with sub-agent. 
This memory can be used by other process.
> Give memory back to system post snmp operation

- snmplib/cert_util.c
- snmplib/snmp_openssl.c
- snmplib/transports/snmpTLSBaseDomain.c
- snmplib/transports/snmpTLSTCPDomain.c
I hope someone will pick it up and continue.
There are now 5-7 failures when running the TLS test suite, if you run without leak checking.
There are a number of leaks that still needs fising too.
> Update V5-90-patches with my fixes for modern OpenSSL

- snmplib/container.c
This fixes 460a97c  "Give memory back to system post snmp operation" for BSD and others without the malloc_trim() function.
> Protect malloc_trim() call with configure #ifdef

- agent/mibgroup/hardware/fsys/fsys_mntent.c
ubifs used to be automatically taken into account in UCD-SNMP-MIB::dskTable but commit e3fc76e0ae ("CHANGES: snmpd: Make UCD-SNMP::dskTable dynamic if includeAllDisks is set.") added a verification that drops all filesystems not present in other_fs[] table.
So add 'ubifs' in other_fs[] to fix it.
> Add 'ubifs' to other_fs

- agent/snmpd.c
Fix - When the reconfig flag is set, we "shudown master agent" which closes the socket listening on 161 and then call "init_master_agent" (which internally calls "netsnmp_agent_listen_on") would re-establish the socket on new port without changing the PID of "snmpd".
Use-case where its failing - Though this change works for most of the cases, its failing in a peculiar case where when we send SIGHUP while parallely the snmpwalk is in progress. When we send SIGHUP in this usecase, the socket is closed by "shutdown_master_agent" but a new socket is never re-established by "init_master_agent" no matter how many sighups we sent, the snmp-server is down permanently.
Going to the root of the problem, I see that the bind is successful as kernel returns 0 but netstat(-nlpu) never reports that …
> SIGHUP for handling agent port change

- local/mib2c-conf.d/mfd-interface.m2c
Allows re-initialization of tables, if e.g. a table needs to be registered under a different snmp-context or to a different agent on a different IP. The table can be re-initialized with different configuration.
Problem solved here is that the table info is reset to no configuration before re-initializing. E.g. the snmp indexes are added during initialization, but not removed in shutdown. To make sure we clear all configuration from the table, a memset() was chosen: we start with a clean table.
> mib2c: Fix re-initialization of tables

- agent/mibgroup/ip-mib/data_access/systemstats_linux.c
Linux 6.7 adds a new OutTransmits field to Ip in /proc/net/snmp. This breaks the hard-coded assumptions about the Ip line length. Add compatibility to parse Linux 6.7 Ip header while keep support for previous versions.
> Add Linux 6.7 compatibility parsing /proc/net/snmp

- snmplib/snmpusm.c
Fixes #723.
The leaks are :
```
=================================================================
==snmpd==329330==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 208 byte(s) in 1 object(s) allocated from:
#0 0x7f357aede9a7 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:77
#1 0x7f357946ecad in usm_create_user /home/user/Desktop/net-snmp/snmplib/snmpusm.c:4101
#2 0x7f357946f110 in usm_create_initial_user /home/user/Desktop/net-snmp/snmplib/snmpusm.c:4141
#3 0x7f357947af27 in init_usm_post_config /home/user/Desktop/net-snmp/snmplib/snmpusm.c:5077
#4 0x7f35793e27d2 in snmp_call_callbacks /home/user/Desktop/net-snmp/snmplib/callback.c:360
#5 0x7f35793aa71d in read_premib_configs /home/user/Desktop/net-snmp/snmplib/read_config.c:1114
#6 …
```
> Fix leak in snmpusm.c

- snmplib/callback.c
As select may update the timeout value, the code may not sleep for 100 ms. If timeout is updated, the code will only sleep for 1 ms once and the immediately return from select(2).
Reassign the timeout value in the loop shouldn't be harmful even on systems that don't update the timeout value.
> libsnmp: Reassign timeout value for select(2)

- dist/snmpd.service
- dist/snmptrapd.service
https://github.com/systemd/systemd/blob/6aa8d43ade72e24c9426e604f7fc4b7582b9db7c/NEWS#L72-L73
this target hasn't existed for over a decade
> snmpd/snmptrapd.service: Remove dead syslog.target

- include/net-snmp/types.h
Correct header comment about retry timeout
The header `<net-snmp/types.h>` contains the following [comment](https://github.com/net-snmp/net-snmp/blob/c1a34f3cbc1bf33fb65b125852541b8336e977cf/include/net-snmp/types.h#L302) in `struct snmp_session`:
```C
/** Number of uS until first timeout, then exponential backoff */
```
This is misleading as [according](https://net-snmp-users.narkive.com/g8tqnRhi/timeout-exponentially-backoff#post1) to the mailing list the exponential back-off behaviour was removed in 1998.
I can confirm that the retry timeout is still fixed at the value set in the `timeout` field:
```
sudo tcpdump -i lo udp port 161 & sleep 1 && time snmpget -v 2c -c public -r 3 -t 5 localhost 1.3.6.1.2.1.1.3.0;
[1] 97961
tcpdump: verbose output suppressed, use -v or -vv for full …
```
> Correct header comment about retry timeout

- agent/mibgroup/disman/schedule/schedConf.c
The "while" loop shifts the pointer,
which can cause it to be NULL.
Fixes: 8baf64d4ae616(Re-worked Schedule MIB implementation.)  
Found by RASU JSC
> agent: mibgroup: avoid potential NULL dereference

- net-snmp-create-v3-user.in
net-snmp-create-v3-user has an ability to use AES128, but does not advertise it
> net-snmp-create-v3-user has an option to use -x AES128, but it was not reflected in usage hint

- configure
- configure.d/config_os_misc4
Forward a patch from 2020 that fixed the sysctl for FreeBSD. This allows compilation to complete for current FreeBSD releases.
> FreeBSD: Fix the sysctl() configure test

- man/net-snmp-create-v3-user.1.def
Hi! Noticed the manpage was missing some options for `net-snmp-create-v3-user`:
```
Usage:
net-snmp-create-v3-user [-ro] [-A authpass] [-X privpass]
[-a MD5|SHA|SHA-512|SHA-384|SHA-256|SHA-224] [-x DES|AES|AES128] [username]
```
Missing option for authentication algorithm and missing parameters for encryption algorithms have been documented.
Although case does not matter for `-A` and `-X` (which seems to be its own can of worms that needs to be kept for compatibility), I've switched them around to match the usage string of `net-snmp-create-v3-user --help`.
> Update man page for net-snmp-create-v3-user

- snmplib/container_binary_array.c
This fixes commit ccfcecb (libsnmp: Fix a potential integer overflow in netsnmp_binary_array_get_subset())
> OpenBSD needs explicit include for stdint.h to get SIZE_MAX

- agent/mibgroup/mibII/ipv6.c
Fixes: ebb758e3 (x Fix var_udp6 and var_tcp6 on FreeBSD)
> Fix ipv6.c for DragonflyBSD

- include/net-snmp/library/asn1.h
Fixes: 589e9c56fad29fbbb5b3adb265cc4644d1aca6b8
> libsnmp: Fix OID_LENGTH macro for build with -pedantic

- agent/mibgroup/mibII/ipv6.c
Fixes: ebb758e3 (x Fix var_udp6 and var_tcp6 on FreeBSD)
> Fix ipv6.c for DragonflyBSD (#841)

- .gitattributes
This fixes autoreconf on MSYS2 and possibly other issues.
> Add gitattributes file to use eol=lf for almost all files

- agent/mibgroup/ucd-snmp/diskio_linux.c
- include/net-snmp/agent/ds_agent.h
- man/snmpd.conf.5.def
On Linux, loading the `nbd` driver creates a number of `nbd` devices even if they aren't actually in use. On top of that, QEMU supports using them as fancier loopback devices for manipulating QCOW2 images. So even when they are in use, there may be reasons to exclude them from the SNMP data.
Since I was updating the manpage, I also added the missing documentation for `diskio_exclude_md` from PR #511 
I'm also not a troff expert in any way (only reason I could update the manpage was that it was a copy and paste job) but ending a line in a period seems to insert an extra space into the text. So I rewrapped the text so that none of these lines end in `e.g.`
> Add option to exclude Network Block Devices

- agent/mibgroup/snmp-notification-mib/snmpNotifyFilterTable/snmpNotifyFilterTable_data_storage.c
Hello,
I'm a new contributor looking forward to correct some behavior I found.
After using the `notificationFilter` directive for creating SNMP-NOTIFICATION-MIB notification filter profile, the `snmpNotifyFilterTable` always showed entries with an empty mask (`0x`). The problem was an uninitialized length field.
> notificationFilter: Fix mask data copying

- snmplib/snmpusm.c
This fixes commit d33578d for ubuntu building.
This problem is same as #839
> Fix include stdint.h missing to get SIZE_MAX

- INSTALL
- snmplib/parse.c
Happens on latest Rpi compiler. Also trivial update of INSTALL
> Avoid unused variable warning

- local/mib2c-update
$UPDATE_CURR is an absolute path, prepending ./ does not make sense
> mib2c-update: fix ls breakage introduced in a8cbc8db2e971990ad

- agent/mibgroup/ucd-snmp/proxy.c
set to the callback
we encounter the following crash:
at ./nptl/pthread_kill.c:44
at ./nptl/pthread_kill.c:78
at ./nptl/pthread_kill.c:89
at ../sysdeps/posix/raise.c:26
fmt=fmt@entry=0x7f6e1a718b77 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
str=str@entry=0x7f6e1a716744 "free(): invalid pointer")
at ./malloc/malloc.c:5664
have_lock=0) at ./malloc/malloc.c:4439
at ./malloc/malloc.c:3391
dcache=dcache@entry=0x55781417b010) at agent_handler.c:934
sess=<optimized out>, reqid=<optimized out>, pdu=0x5578141f21a0,
cb_data=<optimized out>) at ucd-snmp/proxy.c:752
--Type <RET> for more, q to quit, c to continue without paging--
orp=orp@entry=0x0, rp=rp@entry=0x5578141d1690, incr_retries=1)
at snmp_api.c:6778
at snmp_api.c:6851
snmpd is terminated abnormally due to the double free for the request …
> proxy:  Return when NETSNMP_CALLBACK_OP_RESEND is

- Makefile.in
- include/net-snmp/system/openbsd8.h
Preemptive, but OpenBSD follows a roughly 6 month release schedule with a simple 0.1 increment each time and there are no plans to diverge from this, so this will be needed in the future. (No big hurry, development code just moved to using 7.7 for a release in a month or so, but seemed worth including as you're working on a release).
> support openbsd8

- local/Makefile.in
d3a541a added local/mib2c-conf.d/generic-get-in_addr_t.m2i but the Makefile tries to install generic-get-inaddr_t.m2i resulting in "install: ./mib2c-conf.d/generic-get-inaddr_t.m2i: No such file or directory"
> use correct filename when installing generic-get-in_addr_t.m2i

- snmplib/container_binary_array.c
The function netsnmp_binary_array_release() does not deallocate dynamic char array.
Closes https://github.com/net-snmp/net-snmp/pull/924
> snmplib: add deallocation of container name

- agent/mibgroup/mibII/vacm_vars.c
1. Added error checking in the `ACTION`, `COMMIT`, and `UNDO` blocks. If `access_parse_oid` returns an error, the function terminates with `SNMP_ERR_INCONSISTENTNAME`.
2. Memory allocated for `newGroupName` and `newContextPrefix` is freed only after it is no longer needed (e.g., after calling `vacm_getAccessEntry`).
3. The pointers `newGroupName` and `newContextPrefix` are no longer used after calling `free`.
Triggers found by static analyzer Svace.
Signed-off-by: Anton Moryakov <ant.v.moryakov@gmail.com>
> agent: mibgroup: mibII: fix prevent use-after-free in write_vacmAccessStatus

- agent/mibgroup/disman/schedule/schedConf.c
This fixes issue #864 (Out-of-bounds access in _sched_convert_bits function due to invalid cron_spec input)
> Add error checking to schedConf.c.

- snmplib/parse.c
> libsnmp: Do not truncate AGENT-CAPABILITIES descriptions

- snmplib/scapi.c
Checking the return values ​​of MD5_Update and SHA1_Update in the
sc_hash_type() function. In case of an error, returning SNMPERR_GENERR.
Previously, calls to these functions were not checked, which could lead to
undefined behavior in case of hash errors.
Triggers found by static analyzer Svace.
Signed-off-by: Anton Moryakov [ant.v.moryakov@gmail.com](mailto:ant.v.moryakov@gmail.com)
> snmplib: scapi.c: fix unchecked function result

- local/mib2c-update
The mib2c tool generates source/header files that do not include the name of the MIB (Before `::`).
With this patch it is now possible to specify the generated file name. By default the MIB name is just stripped away.
> Fixed an issue in mib2c-update with broken search path

- agent/mibgroup/utilities/override.c
Avoid memory leak if an allocation fails.
Fixes Coverity 454597
> override.c: Avoid leaking memory in rootoid if an allocation fails

- agent/mibgroup/disman/ping/pingCtlTable.c
Avoid memory leak if an allocation fails.
Fixes Coverity 454608
> pingCtlTable.c: Avoid memory leak if an allocation fails

- agent/mibgroup/disman/ping/pingCtlTable.c
Avoid memory leak if strdup fails.
Fixes Coverity 454615
> pingCtlTable.c: Avoid memory leak if strdup fails

- apps/snmpset.c
Small memory leak fixed when allocating a char* with strdup. The memory is now correctly freed before closing.
I know it is very small and that snmpset binary memory is anyway freed after execution but there are teams using snmpset.c code as a guide to implement snmp set operations in their applications with net-snmp library, and this memory leak could be copied.
> snmpset: fix memory leak

- agent/mibgroup/ucd-snmp/loadave.c
Static analysis reported a potential buffer overflow when accessing maxload[i - 1] for i = 0.
The issue was fixed by:
- Adding a check to ensure i > 0 before accessing maxload[i - 1]
- Using NETSNMP_DEFMAXLOADAVE as a default value for the first element (i == 0)
- Ensuring that the code does not attempt to access memory outside of the maxload array
This change makes the code more robust and avoids undefined behavior.
Signed-off-by: Anton Moryakov <ant.v.moryakov@gmail.com>
> loadave.c: fix out-of-bounds access in loadave_parse_config

- include/net-snmp/system/freebsd16.h
- Add include/net-snmp/system/freebsd16.h (currently inherits freebsd15.h).
- Matches existing pattern for FreeBSD 10–15 headers.
This prepares for FreeBSD 16 while keeping current behavior unchanged.
The patch originated from this FreeBSD PR: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=289351
Signed-off-by: Generic Rikka <rikka.goering@outlook.de>
Tested on: FreeBSD 16-CURRENT
> build/freebsd: add FreeBSD 16 system header
